# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/apps/cron-app'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/apps/sentiment-rpc-server'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/lib/grpc-tools'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/lib/is-ticker-symbol'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'got'
  - package-ecosystem: 'npm'
    directory: '/lib/trader-sdk'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/services/api-service'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'got'
  - package-ecosystem: 'npm'
    directory: '/services/sentiment-service'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/services/templating-service'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/services/trading-services'
    schedule:
      interval: 'weekly'
