version: '3.7'
services:
  admin-ui:
    build:
      context: .
      dockerfile: ./apps/admin-ui/Dockerfile
    ports:
      - '${ADMIN_UI_PORT}:4200'
  nginx:
    volumes:
      - ./.docker/nginx/conf.d/dev-proxy.conf:/etc/nginx/conf.d/proxy.conf
    depends_on:
      - admin-ui
