version: '3.7'
services:
  cron-app:
    image: ${REGISTRY_HOST}/trader-tools/data-service:${GITHUB_SHA_SHORT}
    environment:
      NODE_ENV: 'prod'
  sentiment-api:
    image: ${REGISTRY_HOST}/trader-tools/sentiment-api:${GITHUB_SHA_SHORT}
    environment:
      NODE_ENV: 'prod'
