version: '3.7'
services:
  cron-app:
    build:
      context: .
      dockerfile: ./apps/cron-app/Dockerfile
    ports:
      - '${CRON_PORT}:${CRON_PORT}'
    networks:
      - webnet
    restart: always
  sentiment-api:
    build:
      context: .
      dockerfile: ./apps/sentiment-rpc-server/Dockerfile
    ports:
      - '${SENTIMENT_RPC_PORT}:${SENTIMENT_RPC_PORT}'
    networks:
      - webnet
    restart: always
networks:
  webnet:
