version: '3.7'
services:
  cron-app:
    build:
      context: .
      dockerfile: ./apps/cron-app/Dockerfile
  admin-api:
    build:
      context: .
      dockerfile: ./apps/admin-api/Dockerfile
    ports:
      - '${ADMIN_API_PORT}:${ADMIN_API_PORT}'
  sentiment-api:
    build:
      context: .
      dockerfile: ./apps/sentiment-rpc-server/Dockerfile
    ports:
      - '${SENTIMENT_RPC_PORT}:${SENTIMENT_RPC_PORT}'
  nginx:
    extends:
      file: common-services.yml
      service: nginx-base
    depends_on:
      - cron-app
      - admin-api
      - sentiment-api
