# docker-compose.yml

version: '3.7'
services:
  cron-app:
    build:
      context: .
      dockerfile: ./apps/cron-app/Dockerfile
  admin-api:
    build:
      context: .
      dockerfile: ./apps/admin-api/Dockerfile
      ports:
        - '5050:5050'
  admin-ui:
    build:
      context: .
      dockerfile: ./apps/admin-ui/Dockerfile
      ports:
        - '5025:5025'
  sentiment-api:
    build:
      context: .
      dockerfile: ./apps/sentiment-rpc-server/Dockerfile
      ports:
        - '9090:9090'
  nginx:
    image: nginx:1.19-alpine
    ports:
      - '8020:8020'
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - cron-app
      - admin-api
      - admin-ui
      - sentiment-api
