export default {
    MSFT: 'MSFT',
    EVRI: 'EVRI',
    RKT: 'RKT',
    ABR: 'ABR',
    PLUG: 'PLUG',
    MA: 'MA',
    WMT: 'WMT',
    NET: 'NET',
    SRPT: 'SRPT',
    SNDL: 'SNDL',
    SRAC: 'SRAC',
    TPGY: 'TPGY',
    GME: 'GME',
    APHA: 'APHA',
    CPRX: 'CPRX',
    AHCO: 'AHCO',
    CMI: 'CMI',
    QS: 'QS',
    LAZR: 'LAZR'
};