name: CI Job

on:
    pull_request:
        types: [ synchronize, opened, reopened ]
jobs:
    ci_job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: 12
            - run: node common/scripts/install-run-rush.js install
            - run: node common/scripts/install-run-rush.js test