name: CI Job

on:
    pull_request:
        types: [ synchronize, opened, reopened ]
jobs:
    linter_job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                node-version: 14
            - run: [ -z "find . \( -name node_modules -o -path ./common \) -prune -o -name '*.js' -print" ]
    pr_job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: 14
            - run: node common/scripts/install-run-rush.js install
            - run: node common/scripts/install-run-rush.js test