name: CI Job

on:
    pull_request:
        branches: [ master ]
jobs:
    job_1_name:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: 12
            - run: npm i -g rush
            - run: rush update
            - run: rush compile
            - run: rush test