name: Update Dependencies

permissions:
  pull-requests: write
  repository-projects: write
  contents: write

on:
  schedule:
    - cron: '0 3 * * 2'

jobs:
  linter_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 14
      - run: chmod +x "${GITHUB_WORKSPACE}/.github/scripts/build-file-linter.sh"
      - run: '${GITHUB_WORKSPACE}/.github/scripts/build-file-linter.sh'
  dot_only_linter_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 14
      - run: chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dot-only-test-linter.sh"
      - run: '${GITHUB_WORKSPACE}/.github/scripts/dot-only-test-linter.sh'
  eslint_linter_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: node common/scripts/install-run-rush.js update
      - run: node common/scripts/install-run-rush.js lint
  prettier_linter_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: node common/scripts/install-run-rush.js update
      - run: node common/scripts/install-run-rush.js prettier
  pr_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: node common/scripts/install-run-rush.js update
      - run: node common/scripts/install-run-rush.js test
  dependabot-update:
    runs-on: ubuntu-latest
    needs: [linter_job, dot_only_linter_job, eslint_linter_job, prettier_linter_job, pr_job]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          node-version: 14
      - name: Update Lock File
        run: node common/scripts/install-run-rush.js update
      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          message: 'Updated project dependencies'
          default_author: github_actions
